### ISSUE TITLE
Resolver problema

### ISSUE THREAD

**Issue by cataleze** [proyecto-oilstone/assets#31]
Tengo un vehiculo que ademas de documentacion vencida tiene un problema para reparar pero no me aparece el boton resolver problema

**Comment by tomasarras** [comment]
Eso es porque en el ciclo de vida del vehiculo, no figura que se pueda acceder a otro estado desde documentacion vencida. Por ahora se debe primero renovar la documentacion y luego informar el problema. Sino podemos modificar el ciclo de vida para hacer que de documentacion vencida pueda ir a informado.

ciclo de vida: https://app.mural.co/t/proyectooilstone0718/m/proyectooilstone0718/1642533014188/635df7ea3d4134d83c555c9847cc388891190e3e?sender=u54a2e2da32ccbabd11350598
