### ISSUE TITLE
Problemas de un vehiculo

### ISSUE THREAD

**Issue by cataleze** [proyecto-oilstone/assets#36]
cuando quedan listados los problemas muestra la descripcion(detalle) y no el nombre del problema

**Comment by tomasarras** [comment]
Sobre eso, pense en la siguiente situacion, que pasa si hay dos problemas que comparten un mismo tipo de problema? al mostrar el titulo del problema en el listado ¿deberia mostrar el titulo 2 veces o la descripcion que es unica?

**Comment by cataleze** [comment]
Solo se mostraria titulo del problema raiz Ej: " Problema de cubiertas" y en la descripcion se podria incluir como texto libre varios problemas de ese problema raiz
