### ISSUE TITLE
Enviar un vehiculo a reparacion

### ISSUE THREAD

**Issue by cataleze** [proyecto-oilstone/assets#37]
como envio un vehiculo a reparacion si el vehiculo esta informado

**Comment by tomasarras** [comment]
Tenes que seleccionar el/los problemas que quieras arreglar para repararlo

**Comment by cataleze** [comment]
Esto cambio a raiz de lo que estuvimos hablando esta mañana.
Ahora van a aparecer 3 botones 
Nuevo Problema - Solicitar Reparacion - Aceptar Reparacion
