### ISSUE TITLE
Demora en el proceso de actualización de datos

### ISSUE THREAD

**Issue by fspiritosi** [proyecto-oilstone/assets#64]
Es lento el refesh de datos, ej. se carga una VTV y no devuelve enseguida la novedad, al usuario le genera dudas de si fue cargado o no el documento, después de un tiempo, aparecen varias cargas

**Comment by cataleze** [comment]
LA DEMORA ES DEBIDO AL ENLACE DE EL PORVENIR, LA EMPRESA ESTA TRABAJANDO PARA MEJORAR EL ENLACE
