### ISSUE TITLE
Estacionamiento

### ISSUE THREAD

**Issue by fspiritosi** [proyecto-oilstone/assets#65]
Teniendo asignado un vehículo, al quererlo enviar a estacionamiento, no figuran Talleres disponibles

**Comment by cataleze** [comment]
@fspiritosi , el estacionamiento se realiza en los Garages que vos cargues, el vehiculo no se estaciona en un Taller , al taller solo se lo envia a reparacion.
En caso de que lo tengas que estacionar por ej, en G&G o Codelco estos deberian estar cargados como Garages en la seccion Garages.

**Comment by fspiritosi** [comment]
Explicada la funcionalidad
